node_id: 1
address: "127.0.0.1:9001"
data_dir: "./data/node1"

peers:
  1: "127.0.0.1:9001"
  2: "127.0.0.1:9002"
  
raft_tick_ms: 100
election_timeout_ticks: 10
heartbeat_timeout_ticks: 1
tcp_workers: 4